include:
  - vdb/milvus.yaml
  - ${CHAINLIT_DATALAYER_COMPOSE:-extern/dummy.yaml}
  - extern/reranker/${RERANKER_PROVIDER:-infinity}.yaml
  - ${TRANSCRIBER_COMPOSE:-extern/dummy.yaml}

x-openrag: &openrag_template
  image: linagoraai/openrag:latest
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ${DATA_VOLUME:-./data}:/app/data
    - ${MODEL_WEIGHTS_VOLUME:-~/.cache/huggingface}:/app/model_weights # Model weights for RAG
    - ./openrag:/app/openrag # For dev mode
    - /$SHARED_ENV:/ray_mount/.env # Shared environment variables
    - ./logs:/app/logs # For dev mode
  ports:
    - ${APP_PORT:-8080}:${APP_iPORT:-8080}
    - ${RAY_DASHBOARD_PORT:-8265}:8265 # Disable when in cluster mode
    - ${CHAINLIT_PORT:-8090}:${CHAINLIT_PORT:-8090}
  networks:
    default:
      aliases:
        - openrag
  env_file:
    - ${SHARED_ENV:-.env}
  shm_size: 10.24gb

services:
  # OpenRAG Indexer UI
  indexer-ui:
    image: linagoraai/indexer-ui:latest
    build:
      context: ./extern/indexer-ui
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:${APP_PORT:-8080}}
      - INCLUDE_CREDENTIALS=${INCLUDE_CREDENTIALS:-false}
    ports:
      - "${INDEXERUI_PORT:-3042}:3000"
    restart: unless-stopped

  # GPU - default
  openrag:
    <<: *openrag_template
    runtime: nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - ""
    depends_on:
      rdb:
        condition: service_started
      milvus:
        condition: service_healthy
  # No GPU
  openrag-cpu:
    <<: *openrag_template
    deploy: {}
    profiles:
      - "cpu"
    depends_on:
      rdb:
        condition: service_started
      milvus:
        condition: service_healthy

  rdb:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root_password}
      - POSTGRES_USER=${POSTGRES_USER:-root}
    volumes:
      - ${DB_VOLUME:-./db}:/var/lib/postgresql/data
    expose:
      - 5432

networks:
  default:
    name: openrag_default
