{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrag-stack.secretName" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env.secrets }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
