"""add file_quota and file_count fields

Revision ID: bd24665e3451
Revises: a1b2c3d4e5f6
Create Date: 2026-02-09 12:18:23.861014

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd24665e3451"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("file_quota", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("file_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "file_count")
    op.drop_column("users", "file_quota")
    # ### end Alembic commands ###
