"""add file_count and file_quota

Revision ID: c224d4befe71
Revises: cd642e4502d8
Create Date: 2026-02-09 15:38:28.565172

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c224d4befe71"
down_revision: str | Sequence[str] | None = "cd642e4502d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("file_quota", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("file_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "file_count")
    op.drop_column("users", "file_quota")
    # ### end Alembic commands ###
