{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openrag-stack.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"  
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"

spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ required "ingress.host must be set when ingress.tls.enabled=true" .Values.ingress.host | quote }}
      {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host must be set when ingress.enabled=true" .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.ingress.paths.openrag.enabled }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: raycluster-head-svc
                port:
                  number: {{ .Values.env.config.RAY_SERVE_PORT }}
          {{- end }}
{{- end }}
