apiVersion: v2
name: openrag-stack
description: A Helm chart for Kubernetes
type: application

version: 0.6.0
appVersion: "2.0.0"

maintainers:
  - name: linagora
    email: openrag@linagora.com
    url: https://github.com/linagora/openrag

home: https://github.com/linagora/openrag
sources:
  - https://github.com/linagora/openrag

dependencies:
  - name: kuberay-operator
    version: "1.4.0"
    repository: "https://ray-project.github.io/kuberay-helm/"
    alias: kuberay
    condition: kuberay.enabled
  - name: postgresql
    version: ">=17.6.0 <19.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: milvus
    version: "5.0.0"
    repository: "https://zilliztech.github.io/milvus-helm/"
    condition: milvus.enabled
  - name: vllm-stack
    alias: vllm
    version: ">=0.1.7 <1.0.0"
    repository: "https://vllm-project.github.io/production-stack"
    condition: vllm.enabled
