import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `dist` is the build output; `mockServiceWorker.js` is generated by MSW
  // (`npx msw init`) and ships its own `/* eslint-disable */` header.
  globalIgnores(['dist', 'public/mockServiceWorker.js']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      'react-refresh/only-export-components': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/incompatible-library': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      // Allow intentionally-unused identifiers prefixed with "_".
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // shadcn/ui primitives and shared component wrappers deliberately co-locate
    // their variant constants, hooks and contexts beside the component (the
    // upstream convention). The Fast-Refresh "one export per file" rule only
    // affects HMR granularity, so it's noise here, not a defect.
    files: ['src/components/**/*.{ts,tsx}', 'src/lib/auth.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // The React-Compiler lint rules don't understand some vendored internals
    // (shadcn's sidebar context, @tanstack/react-table); they report
    // "skipped"/"impure" advisories, not real bugs, on this library code.
    files: ['src/components/**/*.{ts,tsx}'],
    rules: {
      'react-hooks/purity': 'off',
      'react-hooks/incompatible-library': 'off',
    },
  },
])
